version: '3.8'
services:
  postgres:
    image: postgres:13.1-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=userdev
      - POSTGRES_PASSWORD=passdev
      - POSTGRES_DB=game
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local